name: nafacial
description: Nigerian Army Facial Verification System (NAFacial)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  animated_text_kit: ^4.2.2
  lottie: ^2.6.0
  google_fonts: ^5.1.0
  # Biometric authentication
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  crypto: ^3.0.3
  flutter_svg: ^2.0.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  camera: ^0.10.5+9
  camera_android: ^0.10.8+16
  # Using TensorFlow Lite for accurate face detection and recognition
  # tflite_flutter: ^0.9.5 # Commented out due to compatibility issues
  # Using image package for basic face detection instead of ML Kit
  # google_mlkit_face_detection: ^0.5.0
  permission_handler: ^11.3.0
  image: ^4.1.3
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  http: ^1.1.0
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  badges: ^3.1.2
  audioplayers: ^5.2.1
  vibration: ^1.8.4
  flutter_animate: ^4.5.0
  quick_actions: ^1.0.7
  # image_gallery_saver: ^2.0.3
  local_auth: ^2.1.8
  flutter_plugin_android_lifecycle: ^2.0.17
  usb_serial: ^0.5.1
  flutter_secure_storage: ^9.0.0
  # Removed biometric_storage due to Java 17 requirement
  flutter_webrtc: ^0.9.47
  font_awesome_flutter: ^10.6.0
  web_socket_channel: ^2.4.0
  fl_chart: ^0.65.0
  dynamic_color: ^1.6.9
  # OCR for ID card verification
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_commons: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Enable code generation for localizations
  generate: true

  # Explicitly disable tree shaking for icons
  fonts:
    - family: FontAwesome
      fonts:
        - asset: packages/font_awesome_flutter/fonts/fa-brands-400.ttf
          weight: 400
        - asset: packages/font_awesome_flutter/fonts/fa-regular-400.ttf
          weight: 400
        - asset: packages/font_awesome_flutter/fonts/fa-solid-900.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/animations/
    - assets/sounds/
    - assets/favicon/
    - assets/python/
    - assets/models/
